#:kivy 2.1.0


<SettingGridLayout@GridLayout>:
    cols:2
    
    canvas.before:
        Color:
            rgba: 0.5, 0.5, 0.5, 1
        Rectangle:
            # self here refers to the widget i.e FloatLayout
            pos: self.pos
            size: self.size

    Label:
        size_hint: 0.1, 1
        text:"S\nE\nT\nT\nI\nN\nG\nS\n"

        
    BoxLayout:
        Button:
        Button:
        
         
            
